services:
  mongo:
    image: mongo:6
    container_name: varausapp-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
      
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: varausapp-backend
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/test
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    depends_on:
      - mongo
    command: sh -c "npm run seed && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: varausapp-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongo-data-dev:
